# Generated by Django 4.2.7 on 2025-04-15 17:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=100)),
                ('native_region', models.CharField(max_length=200)),
                ('leaf_type', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaves/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeafUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='leaf_lens_app.leaf')),
            ],
        ),
        migrations.CreateModel(
            name='LeafRecognitionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recognized_leaf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaf_lens_app.leaf')),
            ],
            options={
                'verbose_name_plural': 'Leaf recognition histories',
            },
        ),
        migrations.CreateModel(
            name='LeafPrecaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precautions', to='leaf_lens_app.leaf')),
            ],
        ),
        migrations.CreateModel(
            name='LeafCultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivation', to='leaf_lens_app.leaf')),
            ],
        ),
        migrations.CreateModel(
            name='LeafCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='leaf_lens_app.leaf')),
            ],
        ),
        migrations.CreateModel(
            name='LeafBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='leaf_lens_app.leaf')),
            ],
        ),
    ]
